name: Docker

on:
  schedule:
    - cron: '22 23 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  call-workflow-docker-publish:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: GodsVictory/GitOps/.github/workflows/docker-publish.yml@main
